### ISSUE TITLE
making tui-pattern-highlighter easier to use as library

### ISSUE THREAD

**Issue by janstarke** [0watcher/tui-pattern-highlighter#1]
Hello,

thanks for providing this library. I'd like to use it in <https://codeberg.org/janstarke/evtxview>. But at the moment there are some minor issues which make it hard for me:

* could you please delete the `Cargo.lock`? This prevents me from using a recent version of `ratatui` together with `tui-pattern-highlighter`, which is locked on an older version
* the functions `highlight_text` and `highlight_line` parse a regular expression for themselves. I already have a parsed regex and I'd like to pass it as is. Could you add versions which accept a regex instead of a string?

Kind regards, Jan

**Comment by obeyourmaster67** [comment]
Hi,
done, I hope this is what you wanted.
https://crates.io/crates/tui-pattern-highlighter

**Comment by janstarke** [comment]
Yes, nearly it is. Thank you 👍 

Unfortunately I still get 

```
two different versions of crate `ratatui` are being used; two types coming from two different versions of the same crate are different types even if they look the same
```

which results from the fact that I require `0.29.0` of `ratatui`, while `tui-pattern-highlighter` depends on `0.27.0`. I believed that removing `Cargo.lock` removed this limitation and allows users of `tui-pattern-highlighter` to use it with a more recent version of `ratatui`. I was not right. After some manual reading I learned that in semantic versioning, `pre-1.0.0` are never compatible to each other, and in `cargo` different minor versions are not compatible to each other. So, `0.27.0` is assumed to be compatible to any `0.27.x`, but not to any `0.29.y`.

I know that there were some bugfixes between those version, but I do not know if there are changes which have semantic impacts to `tui-pattern-highlighter`. At least I was able to successfully run your tests against `0.29.0` of `ratatui`.

Could you update your dependency list to require `0.29.0` of `ratatui`?

If you still want to support users which require an older version of `ratatui`, I could imagine that you align your versioning to that of `ratatui`; so your next version could be `0.29.0`, which would depend on `0.29.0` (`>=0.29.0, <0.30`) of `ratatui`. Any fixes and addition by you would then be a patch version of `tui-pattern-highlighter`. This way you could provide new features for users of older versions of `ratatui`. For example, if you added a feature in `0.29.17`; you could backport that feature to `0.27.17` (which would depend on `ratatui` `0.27.0`). You could realize this by having two branches: `v0.27` and `v0.29` with comparable `src`, but different dependencies.

Otherwise: `tui-pattern-highlighter` is currently in pre-release-state. You don't need be backward compatible between minor versions.

**Comment by obeyourmaster67** [comment]
ok, I've changed the version to be "<0.30.0"

**Comment by janstarke** [comment]
Works as a charm. Thanks a lot!

Cheers, Jan
